### ISSUE TITLE
Azure AD B2C

### ISSUE THREAD

**Issue by Jeremywhiteley** [moodio/msal-flutter#10]
Does this work with Azure AD B2C?  I just see active directory listed.

**Comment by dwhiteddsoft** [comment]
We use it exclusively for that

**Comment by mswehli** [comment]
Hi, 
yes. I too use it mostly for B2C. But as it uses the platform native libraries, if it works in the standard library it should work in this one too.

**Comment by Jeremywhiteley** [comment]
Great. Does it work with EasyAuth that is built into azure app service.   Hopefully it works with flutter web as well.

**Comment by mswehli** [comment]
@Jeremywhiteley Sorry i'm not too familiar with EasyAuth, but i assume it should work normally with that it would just be based on scopes.
No, at the moment it works only with android and ios.

**Comment by Jeremywhiteley** [comment]
@mswehli I am willing to pay you if you can add support for web to it.  It would be nice to have one package that word with mobile, web and desktop.

**Comment by mswehli** [comment]
@Jeremywhiteley Sure, I could look into it. Could you email me at mahmoud@moodio.co.uk and I could give you more details on my rates.
