### ISSUE TITLE
Deprecated version

### ISSUE THREAD

**Issue by brdacon1** [moodio/msal-flutter#28]
**I'm facing this issue with this package, is there any way around this?**

The plugin `msal_flutter` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of
Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by mswehli** [comment]
Development has moved to a new repository:
https://github.com/Muljin/msal-flutter

Please try using the alpha version (2+) which should have the changes.
