### ISSUE TITLE
Flutter web support

### ISSUE THREAD

**Issue by Jeremywhiteley** [moodio/msal-flutter#7]
Have you gotten this to work with Flutter web as well yet?  I am thinking it should be easy to get it to work with Flutter web.

**Comment by mswehli** [comment]
@Jeremywhiteley not yet actually, haven't actually played around with flutter web yet so not too familiar with it, but if you're working on any flutter apps that include both mobile and web let me know I could give implementing it a go. But for flutter web only projects i imagine it's easier to just use the msaljs library

**Comment by camsethsum** [comment]
By the way why is this package is tagged with WEB support when in fact it is not ready for use?

**Comment by Jeremywhiteley** [comment]
We really need flutter web support
